*------------------------------------------------------------*;
* Computed Code;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
* TRANSFORM: Frq , (Frq - 10) / (40-10);
*------------------------------------------------------------*;
label RANGE_Frq = 'Transformed Frq';
length RANGE_Frq 8;
if Frq eq . then RANGE_Frq = .;
else RANGE_Frq = (Frq - 10) / (40-10);
*------------------------------------------------------------*;
* TRANSFORM: IMP_Income , (IMP_Income - 9000) / (123230-9000);
*------------------------------------------------------------*;
label RANGE_IMP_Income = 'Transformed: Imputed: Income';
length RANGE_IMP_Income 8;
if IMP_Income eq . then RANGE_IMP_Income = .;
else RANGE_IMP_Income = (IMP_Income - 9000) / (123230-9000);
*------------------------------------------------------------*;
* TRANSFORM: Mnt , (Mnt - 9) / (3260-9);
*------------------------------------------------------------*;
label RANGE_Mnt = 'Transformed Mnt';
length RANGE_Mnt 8;
if Mnt eq . then RANGE_Mnt = .;
else RANGE_Mnt = (Mnt - 9) / (3260-9);
*------------------------------------------------------------*;
* TRANSFORM: NumWebVisitsMonth , (NumWebVisitsMonth - 4) / (15-4);
*------------------------------------------------------------*;
label RANGE_NumWebVisitsMonth = 'Transformed: NumWebVisitsMonth';
length RANGE_NumWebVisitsMonth 8;
if NumWebVisitsMonth eq . then RANGE_NumWebVisitsMonth = .;
else RANGE_NumWebVisitsMonth = (NumWebVisitsMonth - 4) / (15-4);
*------------------------------------------------------------*;
* TRANSFORM: Recency , (Recency - 0) / (99-0);
*------------------------------------------------------------*;
label RANGE_Recency = 'Transformed: Recency';
length RANGE_Recency 8;
if Recency eq . then RANGE_Recency = .;
else RANGE_Recency = (Recency - 0) / (99-0);
*------------------------------------------------------------*;
* TRANSFORM: age , (age - 19) / (74-19);
*------------------------------------------------------------*;
label RANGE_age = 'Transformed age';
length RANGE_age 8;
if age eq . then RANGE_age = .;
else RANGE_age = (age - 19) / (74-19);
*------------------------------------------------------------*;
* TRANSFORM: average_purchase , (average_purchase - 0.9) / (139.66666667-0.9);
*------------------------------------------------------------*;
label RANGE_average_purchase = 'Transformed average_purchase';
length RANGE_average_purchase 8;
if average_purchase eq . then RANGE_average_purchase = .;
else RANGE_average_purchase = (average_purchase - 0.9) / (139.66666667-0.9);
*------------------------------------------------------------*;
* TRANSFORM: campaign_acceptance , (campaign_acceptance - 0) / (4-0);
*------------------------------------------------------------*;
label RANGE_campaign_acceptance = 'Transformed campaign_acceptance';
length RANGE_campaign_acceptance 8;
if campaign_acceptance eq . then RANGE_campaign_acceptance = .;
else RANGE_campaign_acceptance = (campaign_acceptance - 0) / (4-0);
*------------------------------------------------------------*;
* TRANSFORM: loyalty , (loyalty - 24) / (47-24);
*------------------------------------------------------------*;
label RANGE_loyalty = 'Transformed loyalty';
length RANGE_loyalty 8;
if loyalty eq . then RANGE_loyalty = .;
else RANGE_loyalty = (loyalty - 24) / (47-24);
