if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'CHILDHOME'
'MARITAL_STATUS'
'MNTCARD_GAMES'
'NUMCATALOGPURCHASES'
'NUMDEALSPURCHASES'
'RANGE_FRQ'
'RANGE_NUMWEBVISITSMONTH'
'RANGE_RECENCY'
'RANGE_CAMPAIGN_ACCEPTANCE'
'RANGE_LOYALTY'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg: Rejected using stepwise selection";
end;
end;
