if NAME="CostPerContact" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Custid" then do;
ROLE="ID";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Dependents" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="DepVar" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="Dt_Customer" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Gender" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="Recomendation" then do;
ROLE="INPUT";
LEVEL="ORDINAL";
ORDER="";
end;
drop DROP;
