if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'AGE'
'CATPURCHASE'
'CLOTHES'
'COSTPERCONTACT'
'CUSTMONTHS'
'DEPVAR'
'DEPENDENTS'
'EDUCATION'
'FRQ'
'GENDER'
'HOUSEKEEPING'
'INCOME'
'KITCHEN'
'MARITAL_STATUS'
'MNT'
'NETPURCHASE'
'RCN'
'RECOMENDATION'
'REVENUEPERPOSITIVEANSWER'
'SMALLAPPLIANCES'
'TOYS'
) then ROLE='INPUT';
else delete;
end;
