*------------------------------------------------------------*;
* Metadata Changes;
*------------------------------------------------------------*;
if upcase(NAME) = "CHILDHOME" then ROLE="REJECTED";
if upcase(NAME) = "COMPLAIN" then ROLE="REJECTED";
if upcase(NAME) = "EDUCATION" then ROLE="REJECTED";
if upcase(NAME) = "IMP_MNTBRANDA__MATERIAL" then ROLE="REJECTED";
if upcase(NAME) = "IMP_MNTSCENARIO" then ROLE="REJECTED";
if upcase(NAME) = "MNTMINIATURES" then ROLE="REJECTED";
if upcase(NAME) = "MNTPAINTING_MATERIAL" then ROLE="REJECTED";
if upcase(NAME) = "NUMSTOREPURCHASES" then ROLE="REJECTED";
if upcase(NAME) = "RANGE_IMP_INCOME" then ROLE="REJECTED";
if upcase(NAME) = "RANGE_MNT" then ROLE="REJECTED";
if upcase(NAME) = "RANGE_NUMWEBVISITSMONTH" then ROLE="REJECTED";
if upcase(NAME) = "RANGE_AGE" then ROLE="REJECTED";
if upcase(NAME) = "RANGE_LOYALTY" then ROLE="REJECTED";
*------------------------------------------------------------*;
* Dropping REJECTED variables
*------------------------------------------------------------*;
if NAME="AcceptedCmp1" then delete;
if NAME="AcceptedCmp2" then delete;
if NAME="AcceptedCmp3" then delete;
if NAME="AcceptedCmp4" then delete;
if NAME="AcceptedCmp5" then delete;
if NAME="Childhome" then delete;
if NAME="Complain" then delete;
if NAME="Dt_Customer" then delete;
if NAME="Education" then delete;
if NAME="Element1" then delete;
if NAME="Element2" then delete;
if NAME="Element3" then delete;
if NAME="Element4" then delete;
if NAME="Element5" then delete;
if NAME="Frq" then delete;
if NAME="Group" then delete;
if NAME="IMP_Income" then delete;
if NAME="IMP_MntBrandA__Material" then delete;
if NAME="IMP_MntScenario" then delete;
if NAME="Kidhome" then delete;
if NAME="Mnt" then delete;
if NAME="MntMiniatures" then delete;
if NAME="MntPainting_Material" then delete;
if NAME="NumStorePurchases" then delete;
if NAME="NumWebVisitsMonth" then delete;
if NAME="RANGE_IMP_Income" then delete;
if NAME="RANGE_Mnt" then delete;
if NAME="RANGE_NumWebVisitsMonth" then delete;
if NAME="RANGE_age" then delete;
if NAME="RANGE_loyalty" then delete;
if NAME="Recency" then delete;
if NAME="Teenhome" then delete;
if NAME="Year_Birth" then delete;
if NAME="Z_CostContact" then delete;
if NAME="Z_Revenue" then delete;
if NAME="age" then delete;
if NAME="average_purchase" then delete;
if NAME="campaign_acceptance" then delete;
if NAME="loyalty" then delete;
