if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'MARITAL_STATUS'
'MNTCARD_GAMES'
'NUMCATALOGPURCHASES'
'NUMDEALSPURCHASES'
'NUMWEBPURCHASES'
'RANGE_FRQ'
'RANGE_RECENCY'
'RANGE_AVERAGE_PURCHASE'
'RANGE_CAMPAIGN_ACCEPTANCE'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg4: Rejected using stepwise selection";
end;
end;
