if NAME="AcceptedCmp1" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="AcceptedCmp2" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="AcceptedCmp3" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="AcceptedCmp4" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="AcceptedCmp5" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="Complain" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="Custid" then do;
ROLE="ID";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="DepVar" then do;
ROLE="TARGET";
LEVEL="BINARY";
ORDER="";
end;
if NAME="Dt_Customer" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Element1" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Element2" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Element3" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Element4" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Element5" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Group" then do;
ROLE="REJECTED";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="Z_CostContact" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Z_Revenue" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
