if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'CHILDHOME'
'COMPLAIN'
'EDUCATION'
'IMP_MNTBRANDA__MATERIAL'
'IMP_MNTSCENARIO'
'MARITAL_STATUS'
'MNTCARD_GAMES'
'MNTMAGAZINES'
'MNTMINIATURES'
'MNTPAINTING_MATERIAL'
'NUMCATALOGPURCHASES'
'NUMDEALSPURCHASES'
'NUMSTOREPURCHASES'
'NUMWEBPURCHASES'
'RANGE_FRQ'
'RANGE_IMP_INCOME'
'RANGE_MNT'
'RANGE_NUMWEBVISITSMONTH'
'RANGE_RECENCY'
'RANGE_AGE'
'RANGE_AVERAGE_PURCHASE'
'RANGE_CAMPAIGN_ACCEPTANCE'
'RANGE_LOYALTY'
) then ROLE='INPUT';
else delete;
end;
