*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_Children 8;
label IMP_Children = 'Imputed Children';
IMP_Children = Children;
if missing(Children) then IMP_Children = 1;
length IMP_EducDeg $25;
label IMP_EducDeg = 'Imputed EducDeg';
IMP_EducDeg = EducDeg;
if EducDeg = '' then IMP_EducDeg = '3 - BSc/MSc';
length IMP_GeoLivArea 8;
label IMP_GeoLivArea = 'Imputed GeoLivArea';
IMP_GeoLivArea = GeoLivArea;
if missing(GeoLivArea) then IMP_GeoLivArea = 4;
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_BirthYear = 'Imputed BirthYear';
length IMP_BirthYear 8;
IMP_BirthYear = BirthYear;
if missing(BirthYear) then IMP_BirthYear = 1968;
label IMP_FirstPolYear = 'Imputed FirstPolYear';
length IMP_FirstPolYear 8;
IMP_FirstPolYear = FirstPolYear;
if missing(FirstPolYear) then IMP_FirstPolYear = 1986;
label IMP_MonthSal = 'Imputed MonthSal';
length IMP_MonthSal 8;
IMP_MonthSal = MonthSal;
if missing(MonthSal) then IMP_MonthSal = 2501.5;
label IMP_PremHealth = 'Imputed PremHealth';
length IMP_PremHealth 8;
IMP_PremHealth = PremHealth;
if missing(PremHealth) then IMP_PremHealth = 162.81;
label IMP_PremLife = 'Imputed PremLife';
length IMP_PremLife 8;
IMP_PremLife = PremLife;
if missing(PremLife) then IMP_PremLife = 25.56;
label IMP_PremMotor = 'Imputed PremMotor';
length IMP_PremMotor 8;
IMP_PremMotor = PremMotor;
if missing(PremMotor) then IMP_PremMotor = 298.61;
label IMP_PremWork = 'Imputed PremWork';
length IMP_PremWork 8;
IMP_PremWork = PremWork;
if missing(PremWork) then IMP_PremWork = 25.67;
